import cors from "cors";
import express, { Request, Response } from "express";
import registerRouter from "./routes/register-routes";
import { doHealthCheck } from "./utils/healthCheck";

const app = express();
const port = process.env.PORT || 3000;

// // Add detailed request logging middleware
// app.use((req: Request, _res: Response, next) => {
//   console.log("\n=== Incoming Request ===");
//   console.log(`Time: ${new Date().toISOString()}`);
//   console.log(`Method: ${req.method}`);
//   console.log(`URL: ${req.url}`);
//   console.log(`Headers:`, req.headers);
//   console.log(`Query:`, req.query);
//   console.log("=======================\n");
//   next();
// });

app.use(express.json()); // for parsing application/json
app.use(express.urlencoded({ extended: true })); // for parsing application/x-www-form-urlencoded
//app.use(helmet());
// app.use(
//   helmet.contentSecurityPolicy({
//     directives: {
//       "default-src": [
//         "'self'",
//         "https://test.heritage.ynet.gov.yk.ca",
//         // "https://yhrp-dev.seekingtangents.com/",
//       ], //<- this is temporary, figure our why the URLs are not relational
//       "base-uri": ["'self'"],
//       "block-all-mixed-content": [],
//       "font-src": ["'self'", "https:", "data:"],
//       "frame-ancestors": ["'self'"],
//       "img-src": ["'self'", "data:"],
//       "object-src": ["'none'"],
//       "script-src": ["'self'"],
//       "script-src-attr": ["'none'"],
//       "style-src": ["'self'", "https:", "'unsafe-inline'"],
//     },
//   })
// );

// Enable CORS with detailed logging
app.use(
  cors({
    origin: "*",
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization"],
  })
);

// Mount the register routes
app.use("/api/register", registerRouter);

app.get("/api/healthCheck", (_req: Request, res: Response) => {
  doHealthCheck(res);
});

let baseWebPath = "/web";

// serves the static files generated by the front-end
app.use(express.static(__dirname + baseWebPath));

// if no other routes match, just send the front-end
app.use((_req: Request, res: Response) => {
  res.sendFile(__dirname + baseWebPath + "/index.html");
});

app.listen(port, () => {
  console.log(`\nAPI server listening on port ${port}`);
  console.log(`Server URL: http://localhost:${port}`);
});
